### ISSUE TITLE
Common instructions for Management 

### ISSUE THREAD

**Issue by Nikhil-Kasukurthi** [GDGVIT/recruitments#3]
Please have the following content in the management tab, where people can choose their companies that they want to write a report on

> Write a report on any one of the companies below could be a potential sponsor for Google Developers Group VIT.
> It should include the following: 
> - Brief introduction of the company 
> -  Possible ways of communication with the company for sponsorship 
> -  If the company has an existing sponsorship portal or a University panel 
> - Detailed analysis on how the company can benefit by sponsoring GDG 
> 
> **Important aspects that need to kept in mind while writing the report:** 
> - GDG is a Non-Profit Organization (NPO) 
> - The sponsorship can be in any form i.e., Monetary/In-Kind 
> 
> Your writing and analytical skills will be tested in this task. 
> Good Luck

**Comment by ashwini0529** [comment]
Done
